# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in mume.gemspec
gemspec

gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"

gem 'tty-prompt', '~> 0.23.1'
gem 'tty-screen', '~> 0.8.1'
gem 'tty-cursor', '~> 0.7.1'
gem "pastel", '~> 0.8.0'